### ISSUE TITLE
This lesson is for PRO members

### ISSUE THREAD

**Issue by 1stevengrant** [markbrown4/egghead-downloader#5]
I updated the `.env` file with my username and password but I get this message when trying to download the videos for a course.

**Comment by markbrown4** [comment]
Hey, can you try checking out the `pro` branch and running again?
I don't currently have a pro account with egghead so it's a little difficult to confirm if it's working or not.

**Comment by 1stevengrant** [comment]
bombs out with 

```
/Users/t4003901/egghead-downloader/src/download.coffee:84
    contentUrlMatch = contentUrl.match(regex);
                                ^

TypeError: Cannot read property 'match' of undefined
    at getVideoID (/Users/t4003901/egghead-downloader/src/download.coffee:70:31)
    at Request._callback (/Users/t4003901/egghead-downloader/src/download.coffee:57:10)
    at Request.self.callback (/Users/t4003901/egghead-downloader/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/t4003901/egghead-downloader/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/t4003901/egghead-downloader/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)


npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/t4003901/.nvm/versions/node/v6.10.1/bin/node" "/Users/t4003901/.nvm/versions/node/v6.10.1/bin/npm" "run" "download" "https://egghead.io/courses/build-complex-layouts-with-css-grid-layout"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! egghead-downloader@1.0.0 download: `coffee src/program.coffee "https://egghead.io/courses/build-complex-layouts-with-css-grid-layout"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egghead-downloader@1.0.0 download script 'coffee src/program.coffee "https://egghead.io/courses/build-complex-layouts-with-css-grid-layout"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the egghead-downloader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee src/program.coffee "https://egghead.io/courses/build-complex-layouts-with-css-grid-layout"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs egghead-downloader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls egghead-downloader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/t4003901/egghead-downloader/npm-debug.log
```

**Comment by geekyMoa** [comment]
Same issue here, seems like it doesn't manage to authenticate properly. Or it loses the authentication when navigating... or you have to request the video with a token. <-- wild speculation. :p

**Comment by imacnu** [comment]
Same problem TypeError: Cannot read property 'match' of undefined

**Comment by markbrown4** [comment]
It took me about 7 months to update it but this should now work with the redesigned egghead ⚡️.

**Comment by joelhooks** [comment]
I’m going to change it so it breaks again in new and interesting ways 😄

**Comment by markbrown4** [comment]
I ❤️ egghead @joelhooks

**Comment by joelhooks** [comment]
We’ve had a hard time with our course download 1 button automation. I’d rather provide this functionality in a sane way for members. 

This project actually makes me have to ponder **not** releasing all of our content free for a week. That makes me sad. We won’t DRM though, so I’ll just keep making it an ever changing puzzle 😀

**Comment by joelhooks** [comment]
Any interest in working with us on making this cli tool official? We’d pay you. joel@egghead.io
