### ISSUE TITLE
I can't download

### ISSUE THREAD

**Issue by rpayanm** [markbrown4/egghead-downloader#7]
Hi,

Thank you for this script, but i can't download this:
https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'download',
1 verbose cli   'https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs' ]
2 info using npm@3.10.10
3 info using node@v6.12.2
4 verbose run-script [ 'predownload', 'download', 'postdownload' ]
5 info lifecycle egghead-downloader@1.0.0~predownload: egghead-downloader@1.0.0
6 silly lifecycle egghead-downloader@1.0.0~predownload: no script for predownload, continuing
7 info lifecycle egghead-downloader@1.0.0~download: egghead-downloader@1.0.0
8 verbose lifecycle egghead-downloader@1.0.0~download: unsafe-perm in lifecycle true
9 verbose lifecycle egghead-downloader@1.0.0~download: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/egghead-downloader/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/rpayanm/Programs/bin/:/home/rpayanm/.composer/vendor/bin:/home/rpayanm/Programs/bin/:/home/rpayanm/.composer/vendor/bin
10 verbose lifecycle egghead-downloader@1.0.0~download: CWD: /tmp/egghead-downloader
11 silly lifecycle egghead-downloader@1.0.0~download: Args: [ '-c',
11 silly lifecycle   'coffee src/program.coffee "https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs"' ]
12 silly lifecycle egghead-downloader@1.0.0~download: Returned: code: 1  signal: null
13 info lifecycle egghead-downloader@1.0.0~download: Failed to exec download script
14 verbose stack Error: egghead-downloader@1.0.0 download: `coffee src/program.coffee "https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid egghead-downloader@1.0.0
16 verbose cwd /tmp/egghead-downloader
17 error Linux 4.9.0-4-amd64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "download" "https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs"
19 error node v6.12.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error egghead-downloader@1.0.0 download: `coffee src/program.coffee "https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs"`
22 error Exit status 1
23 error Failed at the egghead-downloader@1.0.0 download script 'coffee src/program.coffee "https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the egghead-downloader package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     coffee src/program.coffee "https://egghead.io/lessons/react-introduction-to-the-beginner-s-guide-to-reactjs"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs egghead-downloader
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls egghead-downloader
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by markbrown4** [comment]
It looks like you're using an older version of Node there, tested with `v8.9.0` and it works.

The script also only works with courses or series so you'd need to run:
```npm run download https://egghead.io/courses/the-beginner-s-guide-to-reactjs```

If you're after a single video you can just hit "Download in HD" button on egghead.io
